import fs from 'fs-extra';
import path from 'path';
import { execSync } from 'child_process';
import chalk from 'chalk';
import logger from '../system/logger.js';

/**
 * Template Manager
 * Handles project scaffolding from local boilerplates or remote GitHub repositories.
 */
class TemplateManager {
    constructor() {
        this.templates = [
            {
                id: 'static-web',
                name: 'Static Web / Game (HTML5)',
                repo: null, // Local boilerplate creation
                description: 'A minimal HTML5/CSS3/JS structure for games and frontend-only apps.'
            },
            {
                id: 'node-express',
                name: 'Node.js Express (Basic)',
                repo: 'https://github.com/expressjs/express', // Just an example, ideally a boilerplate repo
                description: 'A clean Express.js setup with essential middleware.'
            },
            {
                id: 'python-flask',
                name: 'Python Flask (Starter)',
                repo: 'https://github.com/pallets/flask',
                description: 'Simple Flask API structure with virtualenv support.'
            },
            {
                id: 'rust-cli',
                name: 'Rust CLI Tool',
                repo: 'https://github.com/rust-lang/cargo',
                description: 'Binary project structure with Clap for CLI parsing.'
            },
            {
                id: 'php-laravel',
                name: 'PHP Laravel (Enterprise)',
                repo: 'https://github.com/laravel/laravel',
                description: 'Full-stack Laravel framework setup with Composer support.'
            },
            {
                id: 'ruby-rails',
                name: 'Ruby on Rails (Agile)',
                repo: 'https://github.com/rails/rails',
                description: 'Rapid web development with the Rails framework and SQLite.'
            }
        ];
    }

    /**
     * List all available templates.
     */
    getTemplates() {
        return this.templates;
    }

    /**
     * Bootstrap a new project.
     */
    async bootstrap(templateId, targetDirPath) {
        const template = this.templates.find(t => t.id === templateId);
        if (!template) throw new Error(`Template ${templateId} not found.`);

        console.log(chalk.blue(`🛠️  Scaffolding new project: ${chalk.white(template.name)}...`));
        
        try {
            await fs.ensureDir(targetDirPath);

            // Attempt to clone from GitHub (if repo exists)
            if (template.repo) {
                console.log(chalk.gray(`   - Pulling latest template from GitHub...`));
                try {
                    execSync(`git clone --depth 1 ${template.repo} .`, { cwd: targetDirPath, stdio: 'pipe' });
                    // Clean up .git folder to make it a fresh project
                    await fs.remove(path.join(targetDirPath, '.git'));
                } catch (gitError) {
                    console.log(chalk.yellow(`   ⚠️  Git clone failed or Git not found. Falling back to basic structure...`));
                }
            } else {
                console.log(chalk.gray(`   - Initializing local static structure...`));
                // Just create basics for static web
                await fs.writeFile(path.join(targetDirPath, 'index.html'), `<!DOCTYPE html><html><head><title>${template.name}</title></head><body><h1>${template.name}</h1><p>Ready for AI Forge generation.</p></body></html>`);
            }

            console.log(chalk.green(`✅ Project bootstrapped successfully at ${targetDirPath}`));
            logger.info(`Project created from template ${templateId} at ${targetDirPath}`);
            
            return true;
        } catch (error) {
            logger.error(`Scaffolding failed: ${error.message}`);
            console.error(chalk.red(`❌ Failed to bootstrap project: ${error.message}`));
            
            // Fallback: Create a very basic README if clone fails
            await fs.writeFile(path.join(targetDirPath, 'README.md'), `# New ${template.name}\nGenerated by Xeyal-System.`);
            return false;
        }
    }
}

const templateManager = new TemplateManager();
export default templateManager;
